import User from "../models/User.js";
import jwt from "jsonwebtoken";

// Middleware to protect routes
export const protectRoute = async (req, res, next) => {

    try {

        const token = req.headers.token;           // headers are the extra info provided by the frontend it is like metadata
        if (!token) {
            return res.json({ success: false, message: "Access denied. No token provided." });
        }

        const decoded = jwt.verify(token, process.env.JWT_SECRET);   // checking that the token was generated by our backend only or not

        const user = await User.findById(decoded.userId).select("-password");   // if the user exists in db with verified token save it in req,user to use in different functions
        if (!user) {
            return res.json({ success: false, message: "User not found" });
        }

        req.user = user; // Attach user to request for downstream access
        next();

    } catch (error) {

        console.log(error.message);
        res.json({ success: false, message: "Invalid or expired token" });

    }
};